### PR TITLE
adding a instance var for the model name

### PR DESCRIPTION
**Pull request by gogogarrett**
This creates an instance variable of the model you're presenting. Instead of all the views having `@model` everywhere - this allows you to explicitly specify `@event.title`, `@song.name`, etc.

### CODE REVIEW

**Comment by zavan** [comment]
:+1: 

Good for using rails default scaffolding views.

**Comment by apotonick** [comment]
Should we use `model.class` or the concept name? Guess @gogogarrett is right, model class will be sufficient and cover a polymorphic setup, too.

**Comment by apotonick** [comment]
@zavan Good point, @gogogarrett can you change that? The `Controller` module is meant to be Rails-specific!

**Comment by gogogarrett** [comment]
I think since this is in a rails-specific module as it is then this is fine enough to leave the code where it is.  I don't see a dire need to split this single method into a AR specific module (as it sort of already is in one).

Thoughts?

**Comment by zavan** [comment]
:+1:

**Comment by apotonick** [comment]
This must go into an `ActiveRecord` module for two reasons. First, `#table_name` is AR-specific and I don't want any Rails B$ hardwired into this gem. Second, what if you have a non-AR operation that works on a PORO (chapter 6 will discuss that)? This would break, because the `model` doesn't respond to `table_name`. :kiss:

**Comment by gogogarrett** [comment]
This AR module something you're after?

**Pull request merged**
