### PR TITLE
Feature: Add authorization

### PR DESCRIPTION
**Pull request by fernandes**
Authorization on Trailblazer!

On controller is easy to check authorization, just need to define your action as like this:

```ruby
def action
  run Thing::Action
  render text: "Action Allowed"
rescue Trailblazer::Operation::NotAuthorized
  render text: "Action Not Allowed"
end
```

Of course you can handle this stuff on your `ApplicationController`, so you always rescue from the exception with a shiny beautiful page.

And how define on our operations? Here is a complete example considering every case and option available:

```ruby
class Thing < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD, Policy
    action :create

    model Thing

    # Policy definition for operation
    policy do
      # Strict policy is a behavior that force policies to exists
      # strict :true raises an exception if no policy is defined for operation
      # If you are on Op::Update and theres no update? prepare for an exception!
      # It forces developers to always define a policy for action
      strict true
      
      # If not user is set on params[:current_user], raise Exception
      allow_guest false

      def create?
        user.admin?
      end

      def update?
        user.admin?
      end
    end

    def process(params); self end
  end

  class Update < Create
    action :update
  end
  
  class Publish < Create
    action :update # so will check using `update?` method
  end

  class Index < Create
    policy do
      # If you wanna check the policy used index? instead of create?
      # use policy_action to specify the desired action check
      policy_action :index
      def index?
        true
      end
    end
  end
end
```

And thats it... everything is working! Amazing hun?

### Testing

And what about the tests?

testing for a valid policy (minitest examples)

```ruby
it { Thing::AllowAccess[current_user: admin_user].policy.verify(:create).must_equal (true) }
```

and checking exception for a invalid policy

```ruby
it do
  err = ->{ Thing::NotAllowedAction[current_user: admin_user] }.must_raise Trailblazer::Operation::NotAuthorized
  err.message.must_match /Not Authorized/
end
```

### CODE REVIEW

**Comment by fernandes** [comment]
many non merged stuff here that already has PR open like https://github.com/apotonick/trailblazer/pull/36 https://github.com/apotonick/trailblazer/pull/38 and https://github.com/apotonick/trailblazer/pull/39 so if you'd like to check just authorization support, its on a single commit https://github.com/fernandes/trailblazer/commit/9d62df75d0ff7ad5def98b889ff109f54764f0e7

**Comment by the-ult** [comment]
Hey @fernandes,

This looks great!
Is there an ETA on when this is gonna be merged and released?

**Comment by the-ult** [comment]
Tried the commit and it works great!

Little suggestion though. Could you consider naming user -> current_user?
Since it is pretty confusing when using the user (params[:current_user]) in a user model

```
require 'trailblazer/operation/policy'

class User < ActiveRecord::Base
	# Initialize
	class Create < Trailblazer::Operation
		include CRUD, Policy
		action :create
		model User

		policy do
			# Strict policy is a behavior that force policies to exists
			# strict :true raises an exception if no policy is defined for operation
			# If you are on Op::Update and there is no update? prepare for an exception!
			# It forces developers to always define a policy for action
			strict true

			# If not user is set on params[:current_user], raise Exception
			allow_guest false

			# user == current_user
			# resource == model == user
			def create?
                                # Pundit
				UserPolicy.new(user, resource).create?
			end

			def update?
				UserPolicy.new(user, resource).update?
			end
		end
```

**Comment by fernandes** [comment]
hi @the-ult, glad you liked it

Mr. @apotonick needs to merge... I "finished" this feature, whenever he wants to merge, its ok

I kept the same API Pundit does... thats why its called user and resource is the object you're handling... you don't need to call UserPolicy, but if you wanna, its ok.

When you're in a op like `User::Index` resource will be `User.find(:id)` thats why the idea is to keep the user / resource... An alternative is `method_alias :current_user, :user` so you can call what makes more sense on policy, I (personally) prefer calls `user`

ty :wink:

**Comment by apotonick** [comment]
That looks great!!! :heart: Can I have an overview about the added API. Also, is this the API from pundit?

**Comment by fernandes** [comment]
what info you need beyond PR description? hahahah

I followed the same principle of Pundit, the idea of `create?` `update?`... but adding Pundit would add some much overhead for a single class that I implemented on [Default Policy](https://github.com/apotonick/trailblazer/pull/41/files#diff-942b590483ec9192fcbaf21b5d1a9b2eR4) and voilá... its all ok!

**Comment by fernandes** [comment]
just keeping https://github.com/apotonick/trailblazer/pull/40 once it includes authorization

**Comment by apotonick** [comment]
@the-ult Check this: https://github.com/apotonick/trailblazer/tree/policy

**Comment by the-ult** [comment]
Thanks! Gonna check it out next week and update our trailblazer version.

**Comment by apotonick** [comment]
Cool, I will try and push a new Trb gem out this weekend!

**Pull request closed without merging**
