### PR TITLE
Handling situations where AR's table_name has been overridden with a sch...

### PR DESCRIPTION
**Pull request by HuckyDucky**
...ema and period prefix.

### CODE REVIEW

**Comment by apotonick** [comment]
Hint: when opening a PR that relates to an issue, always link to it in the summary, like this: https://github.com/apotonick/trailblazer/issues/45 (just copy&paste the URL).

**Comment by apotonick** [comment]
In the above-mentioned test is a test for your fix. I couldn't find out how to create a dotted tablename (`admin.bands`) in sqlite, so I leave this up to you.

**Comment by fernandes** [comment]
using rspec mocks would be something like this:

```ruby
catalog_class = class_double("Catalog")
allow(catalog_class).to receive_messages(:table_name => '@public.catalogs')
```

using mocks would solve the problem without touch the database once sqlite **does not** have schemas (what would make impossible to simulate this)

**Comment by HuckyDucky** [comment]
Got it on linking to the issue. That's a good point on the test double @fernandes.

**Comment by HuckyDucky** [comment]
So if I have forked this repo and made that code change, then created a PR, then Nick added the test... How do I get that new test into my fork so that I can make @fernandes 's test double?

And then after that, would I create a new PR? If I do that, what happens to this PR? Please forgive my questions, but I'm new to contributing and I'll only need to learn this once. I appreciate your help.

**Comment by apotonick** [comment]
You could merge my branch into yours to get my test into your codebase.

@fernandes Mocking doesn't work, as this method is called multiple times, at least once in AR and then again in `Operation`. 

However, I am thinking whether or not to include this change, as this is really an edgy edge-case.

**Comment by fernandes** [comment]
what is the problem on being called multiple times? with rspec-mocks its not a problem

you bad boy hahahha :smile:

**Comment by apotonick** [comment]
Yeah, I always wanted to be a bad boy... :stuck_out_tongue_winking_eye: 

So you have to find out when/in which order you want to change the behaviour of the mocked method, and then in the next Rails release, the order changes and our test breaks? :puke: I never use mocking for a reason. :laughing:

**Comment by HuckyDucky** [comment]
This multitenancy is edgy, but every project I've been involved with for the past few years has had some data in disparate data sources, requiring a schema prefix for many. Whether it was Oracle, MySQL, or Postgres.


Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Nick Sutterer <notifications@github.com> </div><div>Date:04/29/2015  5:05 PM  (GMT-05:00) </div><div>To: apotonick/trailblazer <trailblazer@noreply.github.com> </div><div>Cc: HuckyDucky <Adrian.Klingel@illumaware.com> </div><div>Subject: Re: [trailblazer] Handling situations where AR's table_name has been
  overridden with a sch... (#46) </div><div>
</div>You could merge my branch into yours to get my test into your codebase.

@fernandes Mocking doesn't work, as this method is called multiple times, at least once in AR and then again in Operation.

However, I am thinking whether or not to include this change, as this is really an edgy edge-case.

**Comment by apotonick** [comment]
Hey, is there maybe an ActiveRecord method to get the "clean" table name, only?

**Comment by fernandes** [comment]
hummm afaik theres no such method

**Comment by fernandes** [comment]
@apotonick I'm working on a multi tenant app, and now I got into this error... I can handle the test, but we need to use postgresql on travis... its completely possible (already using it here), should we go through this path?

**Comment by fernandes** [comment]
As @apotonick was in doubt if a test case or not, and I was needing this to keep on my project with trailblazer, I added this case on my fork (if you wanna check @HuckyDucky), check the [commit](https://github.com/fernandes/trailblazer/commit/6763c1244d2de8f466e6119c6d881b23ae779b07) (with tests)

**Comment by HuckyDucky** [comment]
Thanks! So ```it's setup_operation_collection_variables!``` and ```setup_operation_collection_variables!```. Nice work.

**Comment by fernandes** [comment]
@HuckyDucky `setup_operation_collection_variables` is because I merged [collection](https://github.com/fernandes/trailblazer/blob/fork/lib/trailblazer/operation.rb#L49) support on my fork, for more info check https://github.com/apotonick/trailblazer/pull/36, you just need the [active_record.rb](https://github.com/fernandes/trailblazer/commit/6763c1244d2de8f466e6119c6d881b23ae779b07#diff-37ca00407b41455908e6a52d58ebf3d1) (using your solution thx! :+1: ) and the tests for [show](https://github.com/fernandes/trailblazer/commit/6763c1244d2de8f466e6119c6d881b23ae779b07#diff-e321ee4a9ed5eb17467376a93e6a6c27R274)

**Comment by apotonick** [comment]
@HuckyDucky Now that we know how to set a dotted table name, can you add a test? I will merge it, then. If you have trouble with the test just say it, I can do it but - as always - "incredibly busy". :wink:

**Pull request merged**
