### PR TITLE
add some configs to readme

### PR DESCRIPTION
**Pull request by mfbmina**
When I follow your readme, all my form objects are named "reform". When I added this new configs everything worked fine!

Example without this configurations: 
```ruby
@form.model_name
=> #<ActiveModel::Name:0x007f83961c14b8 @name="Reform", @klass=#<Class:0x007f8397072340>, @singular="reform", @plural="reforms", @element="reform", @human="Reform", @collection="reforms", @param_key="reform", @i18n_key=:reform, @route_key="reforms", @singular_route_key="reform">
```

Example with this configuration:
```ruby
@form.model_name
=> #<ActiveModel::Name:0x007f8915ae9070 @name="Comment", @klass=#<Class:0x007f8911dd3a78>, @singular="comment", @plural="comments", @element="comment", @human="Comment", @collection="comments", @param_key="comment", @i18n_key=:comment, @route_key="comments", @singular_route_key="comment">
```

### CODE REVIEW

**Comment by apotonick** [comment]
Yeah, that's in the gemgem initializer, isn't it? I want to include that per default in the Rails module of Trb.

**Comment by mfbmina** [comment]
Yes, it is! But if someone follow your README and don't look for this in gemgem, he can't fix this problem. :cry:  Maybe you should add this in readme while you don't add per default in rails module of trb. Certainly it will help someone! :smile:

**Comment by mfbmina** [comment]
Of if you need help, i try to add this per default for you!

**Comment by apotonick** [comment]
Thanks brother!! I have to think about how to add that so it doesn't collide with non-ActiveRecord setups. i don't want to hard-wire Trailblazer to this questionable framework.

**Comment by mfbmina** [comment]
Hmm... It makes sense! The better solution is really keep this unbound of ActiveRecord and Rails. 

If you put this config inside [here](https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/rails/railtie.rb) it will solve?

**Comment by apotonick** [comment]
This is now handled via trailblazer-rails, thanks brother! :heart:

**Pull request closed without merging**
